def get_codes():
    return [
        "L8031",     # BREAST PROSTHESIS, SILICONE OR EQUAL, WITH INTEGRAL ADHESIVE
        "J0900",     # INJECTION, TESTOSTERONE ENANTHATE AND ESTRADIOL VALERATE, UP TO 1 CC
        "Q5008",     # HOSPICE CARE PROVIDED IN INPATIENT PSYCHIATRIC FACILITY
        "J1815",     # INJECTION, INSULIN, PER 5 UNITS
        "L8515",     # PROSTHESIS, EACH
        "L0634",     # DESIGN, CUSTOM FABRICATED
        "E1594",     # CYCLER DIALYSIS MACHINE FOR PERITONEAL DIALYSIS
        "E1235",     # WHEELCHAIR, PEDIATRIC SIZE, RIGID, ADJUSTABLE, WITH SEATING SYSTEM
        "J2710",     # INJECTION, NEOSTIGMINE METHYLSULFATE, UP TO 0.5 MG
        "L6677",     # TERMINAL DEVICE AND ELBOW
        "J9280",     # MITOMYCIN, 5 MG
        "A4405",     # OSTOMY SKIN BARRIER, NON-PECTIN BASED, PASTE, PER OUNCE
        "G8243",     # REPORT
        "L0112",     # INTERFACE MATERIAL, ADJUSTABLE RANGE OF MOTION JOINT, CUSTOM FABRICATED
        "J9110",     # INJECTION, CYTARABINE, 500 MG
        "L5920",     # SYSTEM
        "J3475",     # INJECTION, MAGNESIUM SULFATE, PER 500 MG
        "S0346",     # TRANSMISSIONS, AND ANALYSIS; PER 24-HOUR PERIOD
        "E0143",     # WALKER, FOLDING, WHEELED, ADJUSTABLE OR FIXED HEIGHT
        "G8526",     # SPECIFIED
        "L2106",     # THERMOPLASTIC TYPE CASTING MATERIAL, CUSTOM-FABRICATED
        "G0341",     # INFUSION
        "P2033",     # THYMOL TURBIDITY, BLOOD
        "J9151",     # INJECTION, DAUNORUBICIN CITRATE, LIPOSOMAL FORMULATION, 10 MG
        "Q9952",     # INJECTION, GADOLINIUM-BASED MAGNETIC RESONANCE CONTRAST AGENT, PER ML
        "S5120",     # CHORE SERVICES; PER 15 MINUTES
        "S2202",     # ECHOSCLEROTHERAPY
        "G8534",     # DOCUMENTATION OF AN ELDER MALTREATMENT SCREEN AND FOLLOW-UP PLAN
        "E2383",     # ANY TYPE, ANY SIZE, REPLACEMENT ONLY, EACH
        "T1013",     # SIGN LANGUAGE OR ORAL INTERPRETIVE SERVICES, PER 15 MINUTES
        "J7685",     # UNIT DOSE FORM, PER 300 MILLIGRAMS
        "L5626",     # ADDITION TO LOWER EXTREMITY, TEST SOCKET, HIP DISARTICULATION
        "J1640",     # INJECTION, HEMIN, 1 MG
        "Q9963",     # HIGH OSMOLAR CONTRAST MATERIAL, 350-399 MG/ML IODINE CONCENTRATION, PER ML
        "L5726",     # SWING PHASE CONTROL
        "L2380",     # ADDITION  TO LOWER EXTREMITY, TORSION CONTROL, STRAIGHT KNEE JOINT, EACH JOINT
        "G8039",     # GREATER THAN 100MG/DL
        "L3360",     # SOLE WEDGE, OUTSIDE SOLE
        "E1806",     # WITHOUT RANGE OF MOTION ADJUSTMENT, INCLUDES ALL COMPONENTS AND ACCESSORIES
        "L8001",     # UNILATERAL
        "J1455",     # INJECTION, FOSCARNET SODIUM, PER 1000 MG
        "G9053",     # IN A MEDICARE-APPROVED DEMONSTRATION PROJECT)
        "B4220",     # PARENTERAL NUTRITION SUPPLY KIT; PREMIX, PER DAY
        "L0640",     # MAY INCLUDE SOFT INTERFACE, PENDULOUS ABDOMEN DESIGN, CUSTOM FABRICATED
        "V2199",     # NOT OTHERWISE CLASSIFIED, SINGLE VISION LENS
        "A4456",     # ADHESIVE REMOVER, WIPES, ANY TYPE, EACH
        "C9255",     # INJECTION, PALIPERIDONE PALMITATE, 1 MG
        "A9150",     # NON-PRESCRIPTION DRUGS
        "A7526",     # TRACHEOSTOMY TUBE COLLAR/HOLDER, EACH
        "J9190",     # INJECTION, FLUOROURACIL, 500 MG        
    ]